## Question 1
Create a python file called hw1.ipynb in jupyternotebook
Load the iris dataset like so:
from sklearn.datasets import load_iris
Print the dataset
Copy the output from your terminal and paste it into your report.
Print the shape of the dataset
Copy and paste the output to your report
Print the feature names (columns) of the dataset
Copy and paste to report
Print the targets of the dataset
Copy and paste to report
Print the shape of the targets
Copy and paste to report


In [3]:
from sklearn.datasets import load_iris
import matplotlib.pyplot as plt


In [4]:
iris = load_iris()
data_set = iris.data
print(data_set)


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [6]:
print(data_set.shape)

(150, 4)


In [7]:
print(iris.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [8]:
print(iris.target)
print(iris.target_names)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
['setosa' 'versicolor' 'virginica']


In [9]:
print(iris.target.shape)

(150,)


## Question 2

Import pandas into your script
Convert the dataset into a Pandas Dataframe
Assign the iris feature names to the columns in your Dataframe
Add a column called “CLASS” to your DataFrame which contains the target values from
the dataset
Now print the whole dataFrame
Copy and paste the output to your report
Select and print only the column called “petal length (cm)”, and only rows 5-10
Copy and paste the output to your report
Select and print only the column called “sepal width (cm)” and only rows 7-19
Copy and paste the output to your report
Using Pandas, Print the mean and standard deviation of the column called “sepal length
(cm)”
Copy and paste the output to your report
Using the describe() function from Pandas. Print the output of your Dataframe like so:
df.describe().
Copy and paste the output to your report


In [5]:
import pandas as pd

In [6]:
data_set = pd.DataFrame(data_set)

In [7]:
data_set = pd.DataFrame(iris.data,columns = iris.feature_names)

In [8]:
data_set['CLASS'] = iris.target

In [9]:
print(data_set)

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     CLASS  
0        0  
1

In [15]:
print(data_set['petal length (cm)'].iloc[5:11])

5     1.7
6     1.4
7     1.5
8     1.4
9     1.5
10    1.5
Name: petal length (cm), dtype: float64


In [16]:
print(data_set['sepal length (cm)'].iloc[7:20])

7     5.0
8     4.4
9     4.9
10    5.4
11    4.8
12    4.8
13    4.3
14    5.8
15    5.7
16    5.4
17    5.1
18    5.7
19    5.1
Name: sepal length (cm), dtype: float64


In [17]:
print("Mean ",data_set['sepal length (cm)'].mean(),"Standard Deviation ",data_set['sepal length (cm)'].std())

Mean  5.843333333333335 Standard Deviation  0.8280661279778629


In [18]:
print(data_set.describe())

       sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)       CLASS  
count        150.000000  150.000000  
mean           1.199333    1.000000  
std            0.762238    0.819232  
min            0.100000    0.000000  
25%            0.300000    0.000000  
50%            1.300000    1.000000  
75%            1.800000    2.000000  
max            2.500000    2.000000  


## Question 3
Download the dataset “nba.csv” from icollege.
Load the dataset with pandas.
Print the number of missing values are there in the “College” column.
Copy and paste this to your report
Are there any missing incorrect values in the “Age” column? If so, how many?
Use df.describe on the “Age” column. Is there anything unusual?
Describe your observations in the report.
What can you do to account for the anomalies you find?
Explain 2 options in your report.
How would each of the options you describe affect the statistics of the “Age” column?
Implement both techniques, and use df.describe after each technique to see how
the underlying statistics have changed.
Print the covariance matrix using the “Age” and “Salary” columns. Can we learn anything
useful from this? (Don’t forget missing values) (and, its ok if it’s not very useful)
Include this analysis in your report.

In [10]:
nba_data = pd.read_csv('C:/Users/G.S Ramchandra/Downloads/nba.csv')

In [20]:
print(nba_data['College'].isnull().sum())

85


In [21]:
print(nba_data['Age'])

0      25.0
1      25.0
2      27.0
3      22.0
4      29.0
       ... 
453    26.0
454    24.0
455    26.0
456    26.0
457     NaN
Name: Age, Length: 458, dtype: float64


In [11]:
print(nba_data['Age'].describe())
print(nba_data['Age'].quantile(0.93))

count    457.000000
mean      26.938731
std        4.404016
min       19.000000
25%       24.000000
50%       26.000000
75%       30.000000
max       40.000000
Name: Age, dtype: float64
34.08000000000004


In [23]:
import numpy as np
index_age = nba_data[nba_data['Age'] > 34.9 ].index
nba_data["Age"].drop(index_age, inplace=True)

In [24]:
print(nba_data['Age'].describe())

count    425.000000
mean      26.207059
std        3.606133
min       19.000000
25%       23.000000
50%       26.000000
75%       29.000000
max       34.000000
Name: Age, dtype: float64


In [15]:
import numpy as np
nba_data["Age"] = np.where(nba_data["Age"] >34.9, nba_data['Age'].quantile(0.93),nba_data['Age'])
print(nba_data['Age'].describe())

count    457.000000
mean      26.758337
std        4.017057
min       19.000000
25%       24.000000
50%       26.000000
75%       30.000000
max       34.080000
Name: Age, dtype: float64


In [25]:
print(nba_data[["Age","Salary"]].cov())

                 Age        Salary
Age     1.939536e+01  4.910243e+06
Salary  4.910243e+06  2.734493e+13
